// Predefined recipe database with 20+ recipes
const SEED_RECIPES = [
  {
    title: "Classic Margherita Pizza",
    description: "A traditional Italian pizza with fresh tomatoes, mozzarella, and basil",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Italian",
    tags: ["vegetarian", "comfort-food", "traditional"],
    calories: 320,
    protein: 18,
    carbs: 35,
    fat: 12,
    ingredients: [
      { name: "Pizza dough", amount: "1", unit: "lb", notes: "store-bought or homemade" },
      { name: "San Marzano tomatoes", amount: "1", unit: "can (14oz)", notes: "crushed" },
      { name: "Fresh mozzarella", amount: "8", unit: "oz", notes: "sliced" },
      { name: "Fresh basil leaves", amount: "1/4", unit: "cup", notes: "" },
      { name: "Extra virgin olive oil", amount: "2", unit: "tbsp", notes: "" },
      { name: "Garlic", amount: "2", unit: "cloves", notes: "minced" },
      { name: "Salt", amount: "1", unit: "tsp", notes: "" },
      { name: "Black pepper", amount: "1/2", unit: "tsp", notes: "" }
    ],
    instructions: [
      { stepNumber: 1, description: "Preheat oven to 500°F (260°C) with a pizza stone or baking sheet inside." },
      { stepNumber: 2, description: "Roll out the pizza dough on a floured surface to your desired thickness." },
      { stepNumber: 3, description: "Mix crushed tomatoes with minced garlic, salt, and pepper." },
      { stepNumber: 4, description: "Spread tomato mixture evenly over the dough, leaving a 1-inch border." },
      { stepNumber: 5, description: "Arrange mozzarella slices over the sauce." },
      { stepNumber: 6, description: "Drizzle with olive oil and bake for 12-15 minutes until crust is golden." },
      { stepNumber: 7, description: "Remove from oven and top with fresh basil leaves. Slice and serve immediately." }
    ]
  },
  {
    title: "Spicy Thai Basil Chicken",
    description: "Authentic Thai stir-fry with ground chicken, basil, and aromatic spices",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Thai",
    tags: ["spicy", "quick-meal", "gluten-free"],
    calories: 280,
    protein: 25,
    carbs: 8,
    fat: 16,
    ingredients: [
      { name: "Ground chicken", amount: "1", unit: "lb", notes: "" },
      { name: "Thai basil leaves", amount: "1", unit: "cup", notes: "packed" },
      { name: "Thai chilies", amount: "3-4", unit: "", notes: "bird's eye chilies, chopped" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "small", notes: "diced" },
      { name: "Fish sauce", amount: "2", unit: "tbsp", notes: "" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp", notes: "" },
      { name: "Sugar", amount: "1", unit: "tsp", notes: "" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp", notes: "" },
      { name: "Jasmine rice", amount: "2", unit: "cups", notes: "cooked, for serving" }
    ],
    instructions: [
      { stepNumber: 1, description: "Heat vegetable oil in a large wok or skillet over high heat." },
      { stepNumber: 2, description: "Add minced garlic and chopped chilies, stir-fry for 30 seconds until fragrant." },
      { stepNumber: 3, description: "Add ground chicken and break it up with a spatula. Cook for 3-4 minutes." },
      { stepNumber: 4, description: "Add diced onion and continue cooking for 2 minutes." },
      { stepNumber: 5, description: "Mix fish sauce, oyster sauce, and sugar together, then pour over the chicken." },
      { stepNumber: 6, description: "Stir-fry for 1 minute, then add Thai basil leaves and cook for 30 seconds." },
      { stepNumber: 7, description: "Remove from heat and serve immediately over jasmine rice." }
    ]
  },
  {
    title: "Mediterranean Quinoa Bowl",
    description: "Healthy and nutritious bowl with quinoa, vegetables, and Mediterranean flavors",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Mediterranean",
    tags: ["vegetarian", "healthy", "gluten-free"],
    calories: 380,
    protein: 12,
    carbs: 45,
    fat: 18,
    ingredients: [
      { name: "Quinoa", amount: "1", unit: "cup", notes: "uncooked" },
      { name: "Cherry tomatoes", amount: "2", unit: "cups", notes: "halved" },
      { name: "Cucumber", amount: "1", unit: "large", notes: "diced" },
      { name: "Red bell pepper", amount: "1", unit: "", notes: "diced" },
      { name: "Red onion", amount: "1/2", unit: "", notes: "thinly sliced" },
      { name: "Kalamata olives", amount: "1/2", unit: "cups", notes: "pitted and halved" },
      { name: "Feta cheese", amount: "4", unit: "oz", notes: "crumbled" },
      { name: "Fresh parsley", amount: "1/4", unit: "cup", notes: "chopped" },
      { name: "Extra virgin olive oil", amount: "3", unit: "tbsp", notes: "" },
      { name: "Lemon juice", amount: "2", unit: "tbsp", notes: "fresh" },
      { name: "Dried oregano", amount: "1", unit: "tsp", notes: "" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" }
    ],
    instructions: [
      { stepNumber: 1, description: "Cook quinoa according to package instructions and let cool to room temperature." },
      { stepNumber: 2, description: "In a large bowl, combine cooked quinoa with cherry tomatoes, cucumber, bell pepper, and red onion." },
      { stepNumber: 3, description: "Add kalamata olives and crumbled feta cheese." },
      { stepNumber: 4, description: "In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and pepper." },
      { stepNumber: 5, description: "Pour dressing over the quinoa mixture and toss gently to combine." },
      { stepNumber: 6, description: "Garnish with fresh parsley and serve at room temperature or chilled." }
    ]
  },
  {
    title: "Beef and Broccoli Stir-Fry",
    description: "Classic Chinese-American dish with tender beef and crisp broccoli in savory sauce",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Chinese",
    tags: ["quick-meal", "comfort-food"],
    calories: 320,
    protein: 28,
    carbs: 15,
    fat: 16,
    ingredients: [
      { name: "Beef sirloin", amount: "1", unit: "lb", notes: "thinly sliced" },
      { name: "Broccoli florets", amount: "4", unit: "cups", notes: "" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Fresh ginger", amount: "1", unit: "tbsp", notes: "minced" },
      { name: "Soy sauce", amount: "3", unit: "tbsp", notes: "" },
      { name: "Oyster sauce", amount: "2", unit: "tbsp", notes: "" },
      { name: "Sesame oil", amount: "1", unit: "tsp", notes: "" },
      { name: "Cornstarch", amount: "1", unit: "tbsp", notes: "" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp", notes: "" },
      { name: "White rice", amount: "2", unit: "cups", notes: "cooked, for serving" }
    ],
    instructions: [
      { stepNumber: 1, description: "Mix soy sauce, oyster sauce, sesame oil, and cornstarch in a small bowl." },
      { stepNumber: 2, description: "Heat 1 tbsp vegetable oil in a large wok or skillet over medium-high heat." },
      { stepNumber: 3, description: "Add beef and stir-fry for 2-3 minutes until browned. Remove and set aside." },
      { stepNumber: 4, description: "Add remaining oil, garlic, and ginger. Stir-fry for 30 seconds." },
      { stepNumber: 5, description: "Add broccoli and stir-fry for 3-4 minutes until tender-crisp." },
      { stepNumber: 6, description: "Return beef to the pan and pour sauce over everything." },
      { stepNumber: 7, description: "Stir-fry for 1-2 minutes until sauce thickens. Serve over rice." }
    ]
  },
  {
    title: "Creamy Mushroom Risotto",
    description: "Rich and creamy Italian risotto with wild mushrooms and parmesan cheese",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "MEDIUM",
    category: "MAIN_COURSE",
    cuisine: "Italian",
    tags: ["vegetarian", "comfort-food", "creamy"],
    calories: 420,
    protein: 16,
    carbs: 55,
    fat: 14,
    ingredients: [
      { name: "Arborio rice", amount: "1.5", unit: "cups", notes: "" },
      { name: "Mixed mushrooms", amount: "8", unit: "oz", notes: "shiitake, cremini, oyster" },
      { name: "Vegetable broth", amount: "5", unit: "cups", notes: "warm" },
      { name: "White wine", amount: "1/2", unit: "cup", notes: "dry" },
      { name: "Onion", amount: "1", unit: "medium", notes: "finely diced" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Parmesan cheese", amount: "1", unit: "cup", notes: "grated" },
      { name: "Butter", amount: "3", unit: "tbsp", notes: "" },
      { name: "Fresh thyme", amount: "1", unit: "tbsp", notes: "chopped" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" }
    ],
    instructions: [
      { stepNumber: 1, description: "Heat 1 tbsp butter in a large pan over medium heat. Sauté mushrooms until golden, about 5 minutes. Set aside." },
      { stepNumber: 2, description: "In the same pan, add remaining butter and sauté onion until translucent, about 3 minutes." },
      { stepNumber: 3, description: "Add garlic and rice, stir for 2 minutes until rice is lightly toasted." },
      { stepNumber: 4, description: "Add wine and stir until absorbed. Begin adding warm broth, 1 cup at a time." },
      { stepNumber: 5, description: "Stir constantly and add more broth as it's absorbed. Continue for 18-20 minutes." },
      { stepNumber: 6, description: "When rice is al dente, stir in mushrooms, parmesan, and thyme." },
      { stepNumber: 7, description: "Season with salt and pepper. Serve immediately with extra parmesan." }
    ]
  },
  {
    title: "Chocolate Chip Cookies",
    description: "Classic homemade chocolate chip cookies, soft and chewy on the inside",
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: "EASY",
    category: "DESSERT",
    cuisine: "American",
    tags: ["baking", "sweet", "comfort-food"],
    calories: 180,
    protein: 2,
    carbs: 24,
    fat: 8,
    ingredients: [
      { name: "All-purpose flour", amount: "2.25", unit: "cups", notes: "" },
      { name: "Baking soda", amount: "1", unit: "tsp", notes: "" },
      { name: "Salt", amount: "1", unit: "tsp", notes: "" },
      { name: "Butter", amount: "1", unit: "cup", notes: "softened" },
      { name: "Brown sugar", amount: "3/4", unit: "cup", notes: "packed" },
      { name: "White sugar", amount: "1/2", unit: "cup", notes: "" },
      { name: "Eggs", amount: "2", unit: "large", notes: "" },
      { name: "Vanilla extract", amount: "2", unit: "tsp", notes: "" },
      { name: "Chocolate chips", amount: "2", unit: "cups", notes: "semi-sweet" },
      { name: "Walnuts", amount: "1", unit: "cup", notes: "chopped (optional)" }
    ],
    instructions: [
      { stepNumber: 1, description: "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper." },
      { stepNumber: 2, description: "Mix flour, baking soda, and salt in a medium bowl." },
      { stepNumber: 3, description: "In a large bowl, cream butter and both sugars until light and fluffy." },
      { stepNumber: 4, description: "Beat in eggs one at a time, then vanilla. Gradually mix in flour mixture." },
      { stepNumber: 5, description: "Fold in chocolate chips and walnuts. Drop rounded tablespoons onto baking sheets." },
      { stepNumber: 6, description: "Bake for 9-11 minutes until golden brown. Cool on baking sheets for 2 minutes." },
      { stepNumber: 7, description: "Transfer to wire racks to cool completely." }
    ]
  },
  {
    title: "Chicken Tikka Masala",
    description: "Creamy and aromatic Indian curry with tender chicken in spiced tomato sauce",
    prepTime: 30,
    cookTime: 25,
    servings: 6,
    difficulty: "MEDIUM",
    category: "MAIN_COURSE",
    cuisine: "Indian",
    tags: ["spicy", "creamy", "comfort-food"],
    calories: 380,
    protein: 32,
    carbs: 18,
    fat: 22,
    ingredients: [
      { name: "Chicken thighs", amount: "2", unit: "lbs", notes: "boneless, cut into chunks" },
      { name: "Plain yogurt", amount: "1", unit: "cup", notes: "" },
      { name: "Garam masala", amount: "2", unit: "tbsp", notes: "" },
      { name: "Turmeric", amount: "1", unit: "tsp", notes: "" },
      { name: "Cumin", amount: "1", unit: "tsp", notes: "ground" },
      { name: "Paprika", amount: "1", unit: "tsp", notes: "" },
      { name: "Cayenne pepper", amount: "1/2", unit: "tsp", notes: "" },
      { name: "Tomato sauce", amount: "1", unit: "can (14oz)", notes: "" },
      { name: "Heavy cream", amount: "1", unit: "cup", notes: "" },
      { name: "Onion", amount: "1", unit: "large", notes: "diced" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Fresh ginger", amount: "1", unit: "tbsp", notes: "minced" },
      { name: "Basmati rice", amount: "3", unit: "cups", notes: "cooked, for serving" }
    ],
    instructions: [
      { stepNumber: 1, description: "Mix yogurt with half the garam masala, turmeric, cumin, paprika, and cayenne." },
      { stepNumber: 2, description: "Marinate chicken in yogurt mixture for at least 30 minutes." },
      { stepNumber: 3, description: "Heat oil in a large pot over medium-high heat. Brown chicken pieces and set aside." },
      { stepNumber: 4, description: "In the same pot, sauté onion until golden, about 5 minutes." },
      { stepNumber: 5, description: "Add garlic, ginger, and remaining spices. Cook for 1 minute." },
      { stepNumber: 6, description: "Add tomato sauce and bring to a simmer. Return chicken to pot." },
      { stepNumber: 7, description: "Simmer for 15 minutes, then stir in cream. Serve over basmati rice." }
    ]
  },
  {
    title: "Avocado Toast with Poached Egg",
    description: "Healthy breakfast with creamy avocado, perfectly poached egg, and fresh herbs",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    difficulty: "EASY",
    category: "BREAKFAST",
    cuisine: "American",
    tags: ["healthy", "quick-meal", "vegetarian"],
    calories: 320,
    protein: 16,
    carbs: 28,
    fat: 18,
    ingredients: [
      { name: "Sourdough bread", amount: "4", unit: "slices", notes: "thick-cut" },
      { name: "Avocados", amount: "2", unit: "ripe", notes: "" },
      { name: "Eggs", amount: "4", unit: "large", notes: "" },
      { name: "Lemon juice", amount: "1", unit: "tbsp", notes: "fresh" },
      { name: "Red pepper flakes", amount: "1/2", unit: "tsp", notes: "" },
      { name: "Fresh cilantro", amount: "2", unit: "tbsp", notes: "chopped" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" },
      { name: "Olive oil", amount: "1", unit: "tbsp", notes: "extra virgin" }
    ],
    instructions: [
      { stepNumber: 1, description: "Toast sourdough bread slices until golden and crisp." },
      { stepNumber: 2, description: "Mash avocados with lemon juice, salt, and pepper until creamy." },
      { stepNumber: 3, description: "Bring a pot of water to a gentle simmer. Add a splash of vinegar." },
      { stepNumber: 4, description: "Crack eggs into the simmering water and poach for 3-4 minutes." },
      { stepNumber: 5, description: "Spread mashed avocado on toast slices." },
      { stepNumber: 6, description: "Top each slice with a poached egg and drizzle with olive oil." },
      { stepNumber: 7, description: "Garnish with red pepper flakes and fresh cilantro. Serve immediately." }
    ]
  },
  {
    title: "Greek Salad",
    description: "Fresh and vibrant Mediterranean salad with tomatoes, cucumbers, olives, and feta",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "EASY",
    category: "SALAD",
    cuisine: "Greek",
    tags: ["vegetarian", "healthy", "fresh"],
    calories: 220,
    protein: 8,
    carbs: 12,
    fat: 16,
    ingredients: [
      { name: "Tomatoes", amount: "4", unit: "large", notes: "cut into wedges" },
      { name: "Cucumber", amount: "1", unit: "large", notes: "diced" },
      { name: "Red onion", amount: "1/2", unit: "", notes: "thinly sliced" },
      { name: "Green bell pepper", amount: "1", unit: "", notes: "diced" },
      { name: "Kalamata olives", amount: "1/2", unit: "cup", notes: "pitted" },
      { name: "Feta cheese", amount: "6", unit: "oz", notes: "cubed" },
      { name: "Fresh oregano", amount: "1", unit: "tbsp", notes: "chopped" },
      { name: "Extra virgin olive oil", amount: "1/4", unit: "cup", notes: "" },
      { name: "Red wine vinegar", amount: "2", unit: "tbsp", notes: "" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" }
    ],
    instructions: [
      { stepNumber: 1, description: "Combine tomatoes, cucumber, red onion, and bell pepper in a large bowl." },
      { stepNumber: 2, description: "Add kalamata olives and feta cheese cubes." },
      { stepNumber: 3, description: "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper." },
      { stepNumber: 4, description: "Pour dressing over the salad and toss gently to combine." },
      { stepNumber: 5, description: "Let the salad sit for 10 minutes to allow flavors to meld." },
      { stepNumber: 6, description: "Serve chilled or at room temperature." }
    ]
  },
  {
    title: "Beef Tacos",
    description: "Classic Mexican tacos with seasoned ground beef and fresh toppings",
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Mexican",
    tags: ["quick-meal", "family-friendly"],
    calories: 350,
    protein: 22,
    carbs: 32,
    fat: 16,
    ingredients: [
      { name: "Ground beef", amount: "1.5", unit: "lbs", notes: "80/20 blend" },
      { name: "Taco seasoning", amount: "1", unit: "packet", notes: "or homemade" },
      { name: "Corn tortillas", amount: "12", unit: "", notes: "warmed" },
      { name: "Shredded lettuce", amount: "2", unit: "cups", notes: "" },
      { name: "Diced tomatoes", amount: "1", unit: "cup", notes: "" },
      { name: "Shredded cheese", amount: "1", unit: "cup", notes: "cheddar or Mexican blend" },
      { name: "Sour cream", amount: "1/2", unit: "cup", notes: "" },
      { name: "Salsa", amount: "1/2", unit: "cup", notes: "" },
      { name: "Avocado", amount: "1", unit: "large", notes: "sliced" },
      { name: "Lime wedges", amount: "2", unit: "limes", notes: "for serving" }
    ],
    instructions: [
      { stepNumber: 1, description: "Brown ground beef in a large skillet over medium-high heat, breaking it up with a spoon." },
      { stepNumber: 2, description: "Drain excess fat and add taco seasoning with 1/3 cup water." },
      { stepNumber: 3, description: "Simmer for 5 minutes until sauce thickens." },
      { stepNumber: 4, description: "Warm tortillas according to package instructions." },
      { stepNumber: 5, description: "Fill each tortilla with seasoned beef and desired toppings." },
      { stepNumber: 6, description: "Serve immediately with lime wedges on the side." }
    ]
  },
  {
    title: "Lemon Garlic Salmon",
    description: "Perfectly baked salmon fillets with bright lemon and aromatic garlic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "American",
    tags: ["healthy", "quick-meal", "gluten-free"],
    calories: 280,
    protein: 35,
    carbs: 2,
    fat: 14,
    ingredients: [
      { name: "Salmon fillets", amount: "4", unit: "6-oz pieces", notes: "skin-on or skinless" },
      { name: "Lemon", amount: "2", unit: "", notes: "juiced and zested" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Fresh dill", amount: "2", unit: "tbsp", notes: "chopped" },
      { name: "Olive oil", amount: "3", unit: "tbsp", notes: "" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" },
      { name: "Asparagus", amount: "1", unit: "lb", notes: "trimmed (optional side)" }
    ],
    instructions: [
      { stepNumber: 1, description: "Preheat oven to 425°F (220°C). Line a baking sheet with parchment paper." },
      { stepNumber: 2, description: "Pat salmon fillets dry and season with salt and pepper." },
      { stepNumber: 3, description: "Mix lemon juice, zest, garlic, dill, and olive oil in a small bowl." },
      { stepNumber: 4, description: "Place salmon on baking sheet and brush with lemon mixture." },
      { stepNumber: 5, description: "Add asparagus to the same pan if using. Bake for 12-15 minutes." },
      { stepNumber: 6, description: "Salmon is done when it flakes easily with a fork. Serve immediately." }
    ]
  },
  {
    title: "Vegetarian Buddha Bowl",
    description: "Nutritious and colorful bowl packed with vegetables, grains, and plant-based protein",
    prepTime: 25,
    cookTime: 20,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "International",
    tags: ["vegetarian", "vegan", "healthy", "gluten-free"],
    calories: 420,
    protein: 18,
    carbs: 58,
    fat: 14,
    ingredients: [
      { name: "Quinoa", amount: "1", unit: "cup", notes: "uncooked" },
      { name: "Sweet potato", amount: "2", unit: "medium", notes: "cubed" },
      { name: "Chickpeas", amount: "1", unit: "can (15oz)", notes: "drained and rinsed" },
      { name: "Broccoli florets", amount: "2", unit: "cups", notes: "" },
      { name: "Red cabbage", amount: "1", unit: "cup", notes: "shredded" },
      { name: "Avocado", amount: "1", unit: "large", notes: "sliced" },
      { name: "Pumpkin seeds", amount: "1/4", unit: "cup", notes: "" },
      { name: "Tahini", amount: "3", unit: "tbsp", notes: "" },
      { name: "Lemon juice", amount: "2", unit: "tbsp", notes: "fresh" },
      { name: "Maple syrup", amount: "1", unit: "tbsp", notes: "" },
      { name: "Olive oil", amount: "2", unit: "tbsp", notes: "" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" }
    ],
    instructions: [
      { stepNumber: 1, description: "Cook quinoa according to package instructions and let cool." },
      { stepNumber: 2, description: "Preheat oven to 400°F (200°C). Toss sweet potato cubes with olive oil, salt, and pepper." },
      { stepNumber: 3, description: "Roast sweet potatoes for 20 minutes, flipping halfway through." },
      { stepNumber: 4, description: "Steam broccoli until tender-crisp, about 5 minutes." },
      { stepNumber: 5, description: "Make tahini dressing by whisking tahini, lemon juice, maple syrup, and water." },
      { stepNumber: 6, description: "Divide quinoa among bowls and top with all vegetables and chickpeas." },
      { stepNumber: 7, description: "Drizzle with tahini dressing and garnish with pumpkin seeds." }
    ]
  },
  {
    title: "Chicken Noodle Soup",
    description: "Comforting homemade soup with tender chicken, vegetables, and egg noodles",
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    difficulty: "EASY",
    category: "SOUP",
    cuisine: "American",
    tags: ["comfort-food", "healing", "family-friendly"],
    calories: 280,
    protein: 24,
    carbs: 32,
    fat: 6,
    ingredients: [
      { name: "Chicken breast", amount: "1", unit: "lb", notes: "boneless, skinless" },
      { name: "Egg noodles", amount: "8", unit: "oz", notes: "wide" },
      { name: "Chicken broth", amount: "6", unit: "cups", notes: "low-sodium" },
      { name: "Carrots", amount: "3", unit: "medium", notes: "diced" },
      { name: "Celery", amount: "3", unit: "stalks", notes: "diced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "diced" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Fresh thyme", amount: "1", unit: "tbsp", notes: "" },
      { name: "Bay leaves", amount: "2", unit: "", notes: "" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" },
      { name: "Fresh parsley", amount: "2", unit: "tbsp", notes: "chopped" }
    ],
    instructions: [
      { stepNumber: 1, description: "Season chicken with salt and pepper. Cook in a large pot until golden, then set aside." },
      { stepNumber: 2, description: "In the same pot, sauté onion, carrots, and celery for 5 minutes." },
      { stepNumber: 3, description: "Add garlic and cook for 1 minute until fragrant." },
      { stepNumber: 4, description: "Add chicken broth, thyme, and bay leaves. Bring to a boil." },
      { stepNumber: 5, description: "Return chicken to pot and simmer for 20 minutes." },
      { stepNumber: 6, description: "Remove chicken, shred it, and return to pot with egg noodles." },
      { stepNumber: 7, description: "Cook noodles according to package directions. Remove bay leaves and garnish with parsley." }
    ]
  },
  {
    title: "Banana Bread",
    description: "Moist and flavorful homemade banana bread, perfect for breakfast or snacks",
    prepTime: 15,
    cookTime: 60,
    servings: 12,
    difficulty: "EASY",
    category: "DESSERT",
    cuisine: "American",
    tags: ["baking", "breakfast", "vegetarian"],
    calories: 220,
    protein: 4,
    carbs: 38,
    fat: 7,
    ingredients: [
      { name: "Ripe bananas", amount: "3", unit: "medium", notes: "mashed" },
      { name: "All-purpose flour", amount: "2", unit: "cups", notes: "" },
      { name: "Baking soda", amount: "1", unit: "tsp", notes: "" },
      { name: "Salt", amount: "1/2", unit: "tsp", notes: "" },
      { name: "Butter", amount: "1/2", unit: "cup", notes: "softened" },
      { name: "Brown sugar", amount: "3/4", unit: "cup", notes: "packed" },
      { name: "Eggs", amount: "2", unit: "large", notes: "" },
      { name: "Vanilla extract", amount: "1", unit: "tsp", notes: "" },
      { name: "Walnuts", amount: "1/2", unit: "cup", notes: "chopped (optional)" }
    ],
    instructions: [
      { stepNumber: 1, description: "Preheat oven to 350°F (175°C). Grease a 9x5-inch loaf pan." },
      { stepNumber: 2, description: "Mix flour, baking soda, and salt in a medium bowl." },
      { stepNumber: 3, description: "Cream butter and brown sugar until light and fluffy." },
      { stepNumber: 4, description: "Beat in eggs one at a time, then vanilla and mashed bananas." },
      { stepNumber: 5, description: "Gradually mix in flour mixture until just combined." },
      { stepNumber: 6, description: "Fold in walnuts if using. Pour batter into prepared pan." },
      { stepNumber: 7, description: "Bake for 60-65 minutes until a toothpick inserted comes out clean. Cool before slicing." }
    ]
  },
  {
    title: "Shrimp Scampi",
    description: "Classic Italian-American dish with succulent shrimp in garlic butter sauce",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Italian",
    tags: ["seafood", "quick-meal", "elegant"],
    calories: 340,
    protein: 28,
    carbs: 32,
    fat: 12,
    ingredients: [
      { name: "Large shrimp", amount: "1.5", unit: "lbs", notes: "peeled and deveined" },
      { name: "Linguine", amount: "12", unit: "oz", notes: "or spaghetti" },
      { name: "Butter", amount: "4", unit: "tbsp", notes: "" },
      { name: "Olive oil", amount: "2", unit: "tbsp", notes: "" },
      { name: "Garlic", amount: "6", unit: "cloves", notes: "minced" },
      { name: "White wine", amount: "1/2", unit: "cup", notes: "dry" },
      { name: "Lemon juice", amount: "2", unit: "tbsp", notes: "fresh" },
      { name: "Red pepper flakes", amount: "1/4", unit: "tsp", notes: "" },
      { name: "Fresh parsley", amount: "1/4", unit: "cup", notes: "chopped" },
      { name: "Parmesan cheese", amount: "1/2", unit: "cup", notes: "grated" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" }
    ],
    instructions: [
      { stepNumber: 1, description: "Cook pasta according to package directions until al dente. Reserve 1 cup pasta water." },
      { stepNumber: 2, description: "Season shrimp with salt and pepper." },
      { stepNumber: 3, description: "Heat butter and olive oil in a large skillet over medium-high heat." },
      { stepNumber: 4, description: "Add shrimp and cook for 2-3 minutes per side until pink. Remove and set aside." },
      { stepNumber: 5, description: "Add garlic and red pepper flakes to the same pan. Cook for 30 seconds." },
      { stepNumber: 6, description: "Add wine and lemon juice, bring to a simmer. Return shrimp to pan." },
      { stepNumber: 7, description: "Toss with cooked pasta, adding pasta water as needed. Garnish with parsley and parmesan." }
    ]
  },
  {
    title: "Caesar Salad",
    description: "Classic Caesar salad with crisp romaine, homemade croutons, and creamy dressing",
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: "MEDIUM",
    category: "SALAD",
    cuisine: "American",
    tags: ["classic", "creamy", "vegetarian"],
    calories: 280,
    protein: 12,
    carbs: 18,
    fat: 20,
    ingredients: [
      { name: "Romaine lettuce", amount: "2", unit: "heads", notes: "chopped" },
      { name: "Bread", amount: "4", unit: "slices", notes: "day-old, cubed" },
      { name: "Parmesan cheese", amount: "1/2", unit: "cup", notes: "grated" },
      { name: "Egg yolks", amount: "2", unit: "large", notes: "room temperature" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Anchovy fillets", amount: "4", unit: "", notes: "minced" },
      { name: "Dijon mustard", amount: "1", unit: "tsp", notes: "" },
      { name: "Worcestershire sauce", amount: "1", unit: "tsp", notes: "" },
      { name: "Lemon juice", amount: "2", unit: "tbsp", notes: "fresh" },
      { name: "Olive oil", amount: "1/2", unit: "cup", notes: "" },
      { name: "Salt and pepper", amount: "", unit: "", notes: "to taste" }
    ],
    instructions: [
      { stepNumber: 1, description: "Preheat oven to 375°F (190°C). Toss bread cubes with olive oil and bake until golden." },
      { stepNumber: 2, description: "Make dressing by whisking egg yolks, garlic, anchovies, mustard, and Worcestershire." },
      { stepNumber: 3, description: "Gradually whisk in lemon juice, then slowly drizzle in olive oil while whisking." },
      { stepNumber: 4, description: "Season dressing with salt and pepper." },
      { stepNumber: 5, description: "Toss romaine lettuce with dressing until well coated." },
      { stepNumber: 6, description: "Top with croutons and parmesan cheese. Serve immediately." }
    ]
  },
  {
    title: "Beef Stir-Fry with Vegetables",
    description: "Quick and colorful stir-fry with tender beef and fresh mixed vegetables",
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: "EASY",
    category: "MAIN_COURSE",
    cuisine: "Asian",
    tags: ["quick-meal", "healthy", "gluten-free"],
    calories: 290,
    protein: 26,
    carbs: 12,
    fat: 16,
    ingredients: [
      { name: "Beef sirloin", amount: "1", unit: "lb", notes: "thinly sliced" },
      { name: "Mixed vegetables", amount: "4", unit: "cups", notes: "bell peppers, broccoli, snap peas" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Fresh ginger", amount: "1", unit: "tbsp", notes: "minced" },
      { name: "Soy sauce", amount: "3", unit: "tbsp", notes: "low-sodium" },
      { name: "Sesame oil", amount: "1", unit: "tsp", notes: "" },
      { name: "Cornstarch", amount: "1", unit: "tbsp", notes: "" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp", notes: "" },
      { name: "Green onions", amount: "3", unit: "", notes: "chopped" },
      { name: "Sesame seeds", amount: "1", unit: "tbsp", notes: "for garnish" }
    ],
    instructions: [
      { stepNumber: 1, description: "Mix soy sauce, sesame oil, and cornstarch in a small bowl." },
      { stepNumber: 2, description: "Heat 1 tbsp vegetable oil in a large wok over high heat." },
      { stepNumber: 3, description: "Stir-fry beef for 2-3 minutes until browned. Remove and set aside." },
      { stepNumber: 4, description: "Add remaining oil, garlic, and ginger. Stir-fry for 30 seconds." },
      { stepNumber: 5, description: "Add mixed vegetables and stir-fry for 3-4 minutes until crisp-tender." },
      { stepNumber: 6, description: "Return beef to wok and pour sauce over everything." },
      { stepNumber: 7, description: "Stir-fry for 1 minute until sauce thickens. Garnish with green onions and sesame seeds." }
    ]
  },
  {
    title: "Chocolate Lava Cake",
    description: "Decadent individual chocolate cakes with molten chocolate centers",
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: "MEDIUM",
    category: "DESSERT",
    cuisine: "French",
    tags: ["chocolate", "elegant", "restaurant-style"],
    calories: 480,
    protein: 8,
    carbs: 45,
    fat: 32,
    ingredients: [
      { name: "Dark chocolate", amount: "6", unit: "oz", notes: "70% cacao, chopped" },
      { name: "Butter", amount: "6", unit: "tbsp", notes: "unsalted" },
      { name: "Eggs", amount: "3", unit: "large", notes: "room temperature" },
      { name: "Egg yolks", amount: "3", unit: "large", notes: "room temperature" },
      { name: "Sugar", amount: "1/3", unit: "cup", notes: "" },
      { name: "All-purpose flour", amount: "1/4", unit: "cup", notes: "" },
      { name: "Salt", amount: "1/4", unit: "tsp", notes: "" },
      { name: "Vanilla ice cream", amount: "", unit: "", notes: "for serving" },
      { name: "Powdered sugar", amount: "", unit: "", notes: "for dusting" }
    ],
    instructions: [
      { stepNumber: 1, description: "Preheat oven to 425°F (220°C). Butter and flour 4 ramekins." },
      { stepNumber: 2, description: "Melt chocolate and butter in a double boiler until smooth. Let cool slightly." },
      { stepNumber: 3, description: "Beat eggs, egg yolks, and sugar until pale and thick, about 5 minutes." },
      { stepNumber: 4, description: "Fold in melted chocolate mixture, then sift in flour and salt." },
      { stepNumber: 5, description: "Divide batter among prepared ramekins." },
      { stepNumber: 6, description: "Bake for 12 minutes until edges are set but centers are still jiggly." },
      { stepNumber: 7, description: "Let cool for 1 minute, then invert onto plates. Serve with ice cream and dust with powdered sugar." }
    ]
  }
];

module.exports = { SEED_RECIPES };
